bundle:
	redoc-cli bundle index.yaml  --options.jsonSampleExpandLevel=all --options.menuToggle --options.nativeScrollbars --options.requiredPropsFirst --options.sortPropsAlphabetically --title "Cargo - API Documentation"
watch:
	redoc-cli serve index.yaml -p 1234 --watch --ssr --options.jsonSampleExpandLevel=all --options.menuToggle --options.nativeScrollbars --options.requiredPropsFirst --options.sortPropsAlphabetically
